### PR TITLE
Friendly reminder to run composer install

### PR DESCRIPTION
**Pull request by QwertyZW**

### CODE REVIEW

**Comment by astorm** [comment]
@QwertyZW Thank you for this pull request.  I'm open to this change -- but could you describe the specific use-case/error that  you're try to solve here?  I'm not sure that an `if` check in the global code space is the best place for this check, but without knowing your use case for sure I can't say (or test!) where the place place would be.

**Comment by QwertyZW** [comment]
As you can probably tell I was playing around with the pestle codebase for quite a bit, and the first problem that I ran into is the require right before where I added the check started failing because I skipped the dev instructions. It took me quite a bit before I realized I had forgotten to run composer install, I figured a helpful message would probably be more helpful than a cryptic looking stack trace.

Obviously this check isn't required once the .phar is produced.  I initially thought about adding the check to getBaseProjectDir(), but I figured if I put the check where it currently is we'd avoid having to stat vendor/autoload.php everytime getBaseProjectDir is called.

**Comment by astorm** [comment]
@QwertyZW Do you remember how you were invoking your dev version of pestle back then?

**Comment by QwertyZW** [comment]
I tried several approaches to see if it changed things. First thing I did was ./pestle_dev and then I tried invoking runner.php directly after I saw the require('./runner.php') in pestle_dev

**Comment by astorm** [comment]
Got it. All that said it feels like the right place for this check would be inside the `main` function in 

    #File: runner.php
    function main($argv)
    {
        //put "has composer run" check right here
        
        include 'modules/pulsestorm/pestle/runner/module.php';
        \Pulsestorm\Pestle\Runner\main($argv);
    }
    
The main purpose of `runner.php` is to invoke pestle via the `pestle_dev` script, so it makes sense to have it there.

Also, when we build the phar, we use `phar-stub.php `

    #File: phar-stub.php 
    #!/usr/bin/env php
    <?php
    function main($argv)
    {
        Phar::mapPhar('pestle.phar');
        include 'phar://pestle.phar/modules/pulsestorm/pestle/runner/module.php';
        \Pulsestorm\Pestle\Runner\main($argv);
    }
    main($argv);
    __HALT_COMPILER();    
    
i.e. The phar doesn't use `runner.php`, so the composer check makes even more sense in `runner.php`.

Happy to accept a pull request along the lines outlined above.

**Comment by QwertyZW** [comment]
Got it. Will close this one and open a new one when done.

**Pull request closed without merging**
