### PR TITLE
#230 Change up crud generation so Repositories use resource models to…

### LINKED ISSUE #230: Change up crud generation so Repositories use resource models to load/save/delete

### PR DESCRIPTION
**Pull request by VincentMarmiesse**
Hello,

I'm beginning the work to resolve #230, do not hesitate to tell me if that's the approch you wanted to do.

Some remarks/questions:

- I'm not sure about the way I retrieve the `Repository` name
- Do I have to edit both `library/all.php` and `modules/pulsestorm/magento2/cli/generate/XXX` everytime? I don't know what is used `all.php` for.
- How can I test my changes on my local environment?

Thanks!

### CODE REVIEW

**Comment by astorm** [comment]
@VincentMarmiesse That you for this, and for your other contributions.  Re: all.php -- no, you don't need to update this.  This file is generated whenever we do a formal release of pestle.  Its generated via the `build-library.bash` script.  You can leave edits to this file out (its there to provide a simple way for folks to use code from pestle modules in their own projects.)

Re: testing locally, you can build a `.phar` from source with the `./build.sh` script in the root of the repository.  This is actually just a wrapper for the `phing` build scripts.    If you don't like the build steps, there's some information on using the `runner.php` file to try out your code https://github.com/astorm/pestle/wiki/Using-Pestle.  I personally setup a `pestle_dev` script that's in a folder that's in my unix path and looks something like this

    #File: ~/bin/pestle_dev
    #!/usr/bin/env php
    <?php
    require_once('/Users/alanstorm/Documents/github/astorm/pestle/runner.php');

That lets me run commands like this

    pestle_dev list

There's a `.travis.yml` file that shows how we run unit and integration tests.  

If you have any other questions, or anything I've said above doesn't make sense please let us know.  We're not setup great for on-boarding new developers at the moment and I'd like to take this as an opportunity to figure out where the pain points are

Re: *I'm not sure about the way I retrieve the Repository name*  I'll need to get back to you on that when I have a moment to remember the context of #230, but top of my head without thinking about it I'd look at the module that generates the repository and see how its naming it.  There's probably a function that does it, and you can just important that function where you need to.

**Comment by VincentMarmiesse** [comment]
Hi @astorm,

> I'd look at the module that generates the repository and see how its naming it. There's probably a function that does it, and you can just important that function where you need to.

Yes that's what I did.

I'll try to build it locally and get back to you!

**Comment by VincentMarmiesse** [comment]
Hi @astorm,

Did you find some time to take a look at this PR?

I have the following error when I launch `./build.sh`:

```
pestle version and latest tag do not match, bailing
```

I have to push a tag on my repo?

EDIT: I have commented the line which throw this error and it seems to work even if I have the following errors:

```
/home/vma/www/pestle/build.xml:41:117: /home/vma/www/pestle/build.xml:41:117: Problem creating package: unable to create temporary file
#0 /home/vma/www/pestle/vendor/phing/phing/classes/phing/UnknownElement.php(100): PharPackageTask->main()
#1 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#2 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#3 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#4 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#5 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('package_phar')
#6 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#7 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#8 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#9 /home/vma/www/pestle/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#10 /home/vma/www/pestle/vendor/phing/phing/bin/phing(14): require_once('/home/vma/www/p...')
#11 {main}

Previous BadMethodCallException: unable to create temporary file in /home/vma/www/pestle/vendor/phing/phing/classes/phing/tasks/ext/phar/PharPackageTask.php:301
Stack trace:
#0 /home/vma/www/pestle/vendor/phing/phing/classes/phing/tasks/ext/phar/PharPackageTask.php(301): Phar->compressFiles(4096)
#1 /home/vma/www/pestle/vendor/phing/phing/classes/phing/UnknownElement.php(100): PharPackageTask->main()
#2 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#3 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#4 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#5 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#6 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('package_phar')
#7 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#8 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#9 /home/vma/www/pestle/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#10 /home/vma/www/pestle/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#11 /home/vma/www/pestle/vendor/phing/phing/bin/phing(14): require_once('/home/vma/www/p...')
#12 {main}
```

**Comment by VincentMarmiesse** [comment]
I just pushed a fix because I had to add some `pestle_import`.

**Comment by astorm** [comment]
@VincentMarmiesse I havn't had a chance to look at this yet -- hopefully on Friday or this weekend.

Don't worry about ./build.sh or the combined library file.  This is something that we run right before performing a build for an official tagged release.  Its OK if this file gets out of sync for now.

**Comment by astorm** [comment]
Thanks again for taking this work on @VincentMarmiesse.  This mostly looks great.  There's just one thing that I think would improve the PR and make it ready to merge

Sometimes you call it the repository a `modelRepository`, other times you call it the  `objectRepository`.  I don't have a preference for either one, but it would be great if we could pick one name and stick with it.

**Comment by VincentMarmiesse** [comment]
Hi @astorm,

Nice catch!

I replaced all occurences of `modelRepository` by `objectRepository`.

**Pull request merged**
