### PR TITLE
format files ending with .xml

### PR DESCRIPTION
**Pull request by QwertyZW**

### CODE REVIEW

**Comment by astorm** [comment]
@QwertyZW Thank you for the pull request!  We're very open to the end goals here (assuming those goals are XML configuration files being written out with formatting).  However, the approach you've taken has a few problems.   Happy to reconsider this pull request if its updated, or a new one that's open.  

The first problem: We have a function for formatting XML already -- `Pulsestorm\Xml_Library\formatXmlString`.  You can use it in any module by putting

    pestle_import('Pulsestorm\Xml_Library\formatXmlString');

at the top of the page, and then calling the function.  

Second -- putting the formatting into `writeStringToFile`, while clever/quick -- is the wrong place for this formatting.  The purpose of the `writeStringToFile` to to write **the exact** string to this file.  Your change changes that behavior, and may cause unexpected results for folks who expected their unformatted file to be written out.  Additionally, there's now **no way** for someone using the `writeStringToFile` to write out an XML file that skips this formatting.

We're open to other solutions -- but (unsexy as it may be) the best way to move forward on this isn't this small bit of code in `writeStringToFile`, but instead to change individual modules so they format their XML (using `formatXmlString`) before passing them to `writeStringToFile` -- or perhaps a new `writeFormattedXmlStringToFile`.   This is a discussion though, so happy to consider other approacher.

**Comment by QwertyZW** [comment]
I figured what I was doing was quite a bit of a hack to avoid having to refactor calls to writeStringToFile at the cost of a formatting side effect when writing files that end with .xml, I completely missed the function in Pulsestorm\Xml_Library though. In that case simply refactoring writeStringToFile() to writeStringToFile(formatXmlString()) where appropriate might just suffice. But I guess having a self-explaining writeFormattedXmlStringToFile might have its benefits too.

If you like I can proceed with either approach.

**Comment by astorm** [comment]
@QwertyZW 

>  In that case simply refactoring writeStringToFile() to writeStringToFile(formatXmlString()) where appropriate might just suffice. But I guess having a self-explaining writeFormattedXmlStringToFile might have its benefits too.

Happy to accept either, and it doesn't need to be all at once.  Might be a refactoring that makes more sends to tackle as we encounter one line XML files.

**Comment by QwertyZW** [comment]
Alright, I think I will probably go with writing a writeFormattedXmlStringToFile. As that will allow further customization of said function in the future.

I will close this PR and open a new one when its done.

**Pull request closed without merging**
