### PR TITLE
Add missing status enable const

### PR DESCRIPTION
**Pull request by VincentMarmiesse**

### CODE REVIEW

**Comment by astorm** [comment]
Thanks for the contribution @VincentMarmiesse!  

Quick question -- it looks like this contribution will add a new constant to every generated model.  Is there a reason you'd like this added to pestle?  We try to keep our generated code as generic as possible and only include things the system will need (we're don't always succeed).  

What's the case for adding a STATUS_ENABLED to this model? (not a rhetorical question!  If there's a case we want to hear it!)

**Comment by VincentMarmiesse** [comment]
Hi @astorm,

Indeed, I did this PR because this constant is used in the `Save` controller and does not exist. You can see it [here](https://github.com/astorm/pestle/blob/master/modules/pulsestorm/magento2/cli/magento2/generate/ui/form/module.php#L130) and [here](https://github.com/astorm/pestle/blob/master/library/all.php#L8482).

Maybe it's done on purpose and I should add it if necessary?

**Comment by astorm** [comment]
Ah, thank you.  I'd forgotten to check my own module :)  Nice catch!

Here's some background, and an idea for a more robust feature. 

Originally these commands were created in isolation -- each one meant to the bare minimum necessary to achieve its task.  So the model generating code came first, and then later the UI Component form module command came along.  (the later requiring your models to have that status field). 

I like this addition.  I like that it makes sure models generated with pestle can be used by UI Forms generated by pestle.  However, the purist in me is a little bugged that the model generating code will always generate this constant, even if a developer's not using it.  My first suggestion would be an option on the command for adding constants to your model, something like

    pestle.phar magento2:generate:crud-model --add-constants 'FOO,bar,BAZ=42,1' Pulsestorm_Helloworld Thing

Where the `add-constant` option is comma separated string of key/value pairs of each constant you want added to the class.  

Then we'd need to change the `magento2:generate:full-module` command to generate a `magento2:generate:crud-model` command that generated these status constants. 

It's a little more work, but it'd be keeping more in the spirit of "small commands that do one thing well, and can be linked together to do larger things".  

Do you think you'd be up for that @VincentMarmiesse? (I'm always hesitant to say "thanks for the PR, here's more work" :) )

**Comment by VincentMarmiesse** [comment]
Hi @astorm,
I see what you mean, but I'm not sure it's really useful.

Are we really going to add some constants by command line when we create a CRUD model? Because we have to manually add the use of theses constants anyway in the code.

What do you think about removing the use of `STATUS_ENABLED` and just let the user add his own constant if necessary?

**Pull request closed without merging**
