### PR TITLE
[BUGFIX] Fix wrong return value of simpleXmlAddNodesXpath

### PR DESCRIPTION
**Pull request by cmuench**
Without the patch the last used node object will be returned.

I used some of your code in my current n98-magerun2 code base. I hope that's ok for you (code contains a reference url).

### CODE REVIEW

**Comment by astorm** [comment]
Thanks @cmuench Re: the code, it's open source, so use in whatever projects you like (but thank you for asking!).  Glad it was useful!

Re: this patch -- I need to review the framework, but my memory says that this was a deliberate design decision -- I wanted to return the final node created by the script so the end-user-client programmer could continue to modify the final node if they needed to.  

Finally, this pull request will probably linger for a while until I get an integration/acceptance test suite up and running.   Apologies for that, but hours in the day, still working for a living, etc :)

**Comment by astorm** [comment]
@cmuench Sorry for the 7 months of silence on this one.  Bad news -- we're closing this pull request.  The good news -- we've got a new function that does what you patched `simpleXmlAddNodesXpath` to do **and** we've got a way for you (and others) to use any pestle function from your PHP based application. 

Re: the new function, `simpleXmlAddNodesXpathReturnOriginal` should do what you want.  The "return the created child node" behavior of `simpleXmlAddNodesXpath` was/is intentional, but if you want/need to return the originally passed in XML document node, `simpleXmlAddNodesXpathReturnOriginal` will do what you want.  If we missed some subtlty of the original pull request, please let us know. 

Re: using pestle code in your application -- there's no need for you to do this, i.e. we're MIT license so it's perfectly legitimate to grab a chunk of code and drop it into your own application.  **However**, you can now include pestle via composer and get a simple namespaced library of every function.  Details are [in the README](https://github.com/astorm/pestle#how-to-use-pestle-code-in-your-application).  If you end up going this route, we'd love any feedback you have. 

Thanks again for the pull request -- despite not merging it in it was helpful in shaping the direction of the project and giving us some new functionality to chew over!

**Comment by vrkansagara** [comment]
ok looks good :+1:

**Comment by cmuench** [comment]
👍

**Pull request closed without merging**
