### PR TITLE
Enhance ID column name

### PR DESCRIPTION
**Pull request by VincentMarmiesse**
Hello,

The ID column name is currently `<table_name>_id` so it's not very beautiful, I think it's better to have `<model_name>_id` what do you think?

### CODE REVIEW

**Comment by VincentMarmiesse** [comment]
Could you help me about the error on Travis?
`strtolower` fails on php5.6 but I don't know why.

I noticed you used `strToLower` and not `strtolower`, there is a reason?

**Comment by astorm** [comment]
Re: the travis error -- it appears you uncovered a problem with the CI setup.  If I look at the tests under PHP 7

> phpunit tests
> PHPUnit 6.4.3 by Sebastian Bergmann and contributors.
> Time: 147 ms, Memory: 10.00MB
> No tests executed!

It appears that no tests are actually executing.  I'll be opening a bug to deal with this.

Re: 

> The ID column name is currently <table_name>_id so it's not very beautiful, I think it's better to have <model_name>_id what do you think?

How does Magento name the IDs for its tables?  If things still work with `<model_name>_id` I'm not opposed to it, but its my recollection that Magento expects or uses the `<table_name>_id` convention. (again, this could be incorrect)

**Comment by VincentMarmiesse** [comment]
> How does Magento name the IDs for its tables? If things still work with <model_name>_id I'm not opposed to it, but its my recollection that Magento expects or uses the <table_name>_id convention. (again, this could be incorrect)

Are you sure?
It seems there is no real convention, a lot of tables are using `entity_id` as id, it may be the simplest.
But some other tables use `<model_name>_id`, for example:

- `admin_user` uses `user_id`
- `customer_visitor` uses `visitor_id`
- `quote_item` uses `item_id`

**Comment by astorm** [comment]
FYI: Tests are fixed so they'll run in PHP 7.  https://github.com/astorm/pestle/pull/334

The above PR's been merged into master, so merge/rebase to pickup the change.

**Comment by astorm** [comment]
@VincentMarmiesse Thanks for doing the legwork on that -- I'm OK with the ID name being derived from the model name instead of the table name.

**Comment by VincentMarmiesse** [comment]
@astorm, ok I checked what caused the tests to fail, I had to update them because I have added a new parameter to the `generateInstallSchemaTable` function.
It's ok now :+1:

**Pull request merged**
