### PR TITLE
Events autocompletion

### PR DESCRIPTION
**Pull request by QwertyZW**
## proposed changes ##
1)Adds an arguments tracker loop
2)Adds an autocompletion list for observers `magento2:generate:observer`
-completes only the 2nd argument (the event to observe)
3)Adds logic to trigger completion
4)Adds script used to generate the auto-complete list
-note that I had to manually change this item https://github.com/QwertyZW/pestle/commit/55b70cc12005e109efe76b306342a22f02a8c392

The regex in the capture group can be slightly changed to ignore this case all together

## known caveats ##

1) assumes events are generated by occurence of `.*eventManager->dispatch` in the app/code/Magento directory
2) list is not dynamic (creates limitations and versioning issues mentioned below) 
3) Only catches events that match the regex (details in script).

## other options ##
There might be better ways to generate the list (such as parsing all the php files with ext-ast and figuring out what actually calls ->dispatch from the events manager)

The list can also be generated dynamically, `pcre2grep -r` on the `app/code/Magento` directory doesn't seem to lag my machine (although theoretically it should), and without a change in the script this will require the pcre2grep command to be available (or perhaps change the command to rely only on grep as mentioned [here](https://stackoverflow.com/questions/3717772/regex-grep-for-multi-line-search-needed))

As of this writing the list is only up to date with the 2.1-develop branch. This can be alleviated by versioning the list(independently of pestle) although dynamic generation will be better because it can be made to capture not only the events generated by the `Magento` vendor but by all others as well.

 ## All that said ##
This worked well enough for me

```
khishman@khishman-desktop:~/dev/pestle$ ./pestle.phar -x --long-opt=xx magento2:generate:observer PulseStorm_HelloWorld custom
customer_account_edited          customer_customer_authenticated  customer_login                   customer_register_success        customer_session_init            
customer_address_format          customer_data_object_login       customer_logout                  customer_save_after_data_object  custom_quote_process             
khishman@khishman-desktop:~/dev/pestle$ ./pestle.phar -x --long-opt=xx magento2:generate:observer PulseStorm_HelloWorld customer_
customer_account_edited          customer_customer_authenticated  customer_login                   customer_register_success        customer_session_init            
customer_address_format          customer_data_object_login       customer_logout                  customer_save_after_data_object  
khishman@khishman-desktop:~/dev/pestle$ ./pestle.phar -x --long-opt=xx magento2:generate:observer PulseStorm_HelloWorld customer_register_success 

```

### CODE REVIEW

**Comment by astorm** [comment]
One yolo merge, coming up.

**Comment by astorm** [comment]
@QwertyZW You seem more up on the bas autocomplete stuff than I am -- I noticed that what pestle has now removes the ability to autocomplete a file path as an argument -- do you have any idea how to restore that functionality?

**Comment by QwertyZW** [comment]
@astorm  do you mean that it had it before this merge and this broke it? :S I'm confused

**Comment by QwertyZW** [comment]
@astorm  you can generate file names for suggestions with compgen using `compgen -o filenames -A file`

for example
```
...
#suggest file names
COMPREPLY=( $(compgen -o filenames -A file) )
return 0
...
```

And to autocomplete we pass the current (to be completed `$cur`)
```
...
#autocomplete file names
COMPREPLY=( $(compgen -o filenames -A file $cur) )
return 0
...
```

**Comment by astorm** [comment]
> do you mean that it had it before this merge and this broke it? :S I'm confused

Nope, that's not what I meant.  Your pull request was fine.  I was (confusingly) asking you a different question.  I was asking because you seem more up-to-speed on how all the base auto-complete stuff works.

The problem I want to solve is -- prior to using this bash autocomplete script, the standard bash autocomplete behavior would let you autocomplete paths for commands.  i.e. if you typed

    pestle.phar some:command app/code/Pu

and then hit tab, the path would complete to 

    pestle.phar some:command app/code/Pulsestorm

However, when **I** introduced this simple bash autocomplete script -- this behavior went away.  I assume its my script that's doing it, and the script needs to manually implement file and path auto-complete.  I was hoping you might know how that's done and if there's a bog standard way to get it to work (which is maybe `compgen -o filenames -A file`?)

Hope that helps -- and thanks again for your recent contributions along these lines.

**Comment by QwertyZW** [comment]
@astorm Got it,

By default filenames are suggested as arguements (according to [this](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html))

Default suggestions can also be set by using `complete -D`, those will generate suggestions for a command on which `complete` hasn't been called explicitly. (We're not sure which of the 2 aforementioned methods are generating the defaults in your case, but that shouldn't matter(it's probably the former))

When we do `complete -F _my_autocomplete_function commandname`  we're overriding the default suggestions and telling bash to get the suggestions by capturing the value of the `COMPREPLY` reply variable every time autocompletion is triggered (`[TAB]` key is pressed) which is assumed to be assigned by `_my_autocomplete_function` . We'll no longer get the aforementioned default behavior by doing that.

However we could still generate the default suggestions with ` compgen -o default` (filename completion) and use them appropriately within `_my_autocomplete_function`. To get default behaviour in a certain scenario we'd simply capture the output of  `compgen -o default` into `COMPREPLY`. 

Those suggestions will be useful in places in `_my_autocomplete_function` where we don't know what suggest, as a last resort. (I.e if we can't come up with any meaningful suggestions we simply do `COMPREPLY=$(compgen -o default)` )

This is the way I understand autocomplete,  you shouldn't quote me on it ;-)

**Pull request merged**
