### PR TITLE
#273 Generated code is not PSR-2 compliant [WIP]

### PR DESCRIPTION
**Pull request by VincentMarmiesse**
Hello,

I'm working on resolving issue #273.

I have added the composer dependancy `squizlabs/php_codesniffer` and use the following command to check the PSR2 compliance as Vinai suggested:

```
vendor/bin/phpcs --standard=psr2 <path_to_module>
```

Two issues remain:

- Method name "_construct" should not be prefixed with an underscore to indicate visibility": this issue is caused by extending Magento classes -- should we ignore it?
- The most important IMO, the blank lines after `namespace` and `use` statements. Sometimes it's ok, sometimes there is no blank lines and sometimes there are two blank lines... I need some help on this one, I tried several things and when I fix something, I break something else.

Thanks!

### CODE REVIEW

**Comment by astorm** [comment]
Re:
> Method name "_construct" should not be prefixed with an underscore to indicate visibility": this issue is caused by extending Magento classes -- should we ignore it?

If the `_construct` is in a Magento class there's nothing we can do about it.  Do yes, we'll need to ignore that.  

Re:

> The most important IMO, the blank lines after namespace and use statements. Sometimes it's ok, sometimes there is no blank lines and sometimes there are two blank lines... I need some help on this one, I tried several things and when I fix something, I break something else

Can you give me an example of the command you run, and the spaces you're talking about?  With that I'll better be able to formulate a way of dealing with them.

**Comment by VincentMarmiesse** [comment]
Hi,

I use `vendor/bin/phpcs --standard=psr2 <path_to_the_generated_module>` and I got two kinds of errors:

```
There must be one blank line after the namespace declaration
There must be one blank line after the last USE statement; 0 found;
```

But when I try to fix the namespace error, I sometimes have too blank lines for the classes which doesn't have any use for example.

**Comment by astorm** [comment]
@VincentMarmiesse I meant which pestle commands are you running, and which files have the janky white space.

**Comment by astorm** [comment]
@VincentMarmiesse Just checking in here -- do you have an example of which pestle commands you're running and which files have the non-PSR2 whitespace?  (or, if that's a dumb question on my part, can you educate me on why its dumb? :))

**Comment by VincentMarmiesse** [comment]
Hi,
Sorry for the delay! Your question is not dumb ;)

Please find the report attached, it concerns almost every file when generating a full module.
[psr2.txt](https://github.com/astorm/pestle/files/2136973/psr2.txt)

**Pull request closed without merging**
