### PR TITLE
Remove useless use statements

### PR DESCRIPTION
**Pull request by VincentMarmiesse**
Some use statements are not used into the Repository and its interface.

### CODE REVIEW

**Comment by astorm** [comment]
Thanks for this commit Vincent -- can you let me know which use statement this removes?

**Comment by VincentMarmiesse** [comment]
Hi,
It removes the use of `Magento\Framework\Api\SortOrder` and use the short name of the interface which was already in `use` statements but still called with its full name.

**Comment by astorm** [comment]
@VincentMarmiesse In which files after running which commands?

**Comment by VincentMarmiesse** [comment]
Hi @astorm,

In file `Vendor/Module/Api/<Object>RepositoryInterface.php`, when I launch the `magento2:generate:crud-model` command.

**Comment by astorm** [comment]
Got it -- you're correct that the repository interfaces don't need to important that interface, and the changed function (`templateRepositoryInterfaceUse`) isn't used elsewhere.  Merging!

**Pull request merged**
