### PR TITLE
allow custom controller and action names

### PR DESCRIPTION
**Pull request by QwertyZW**
Defaults to \Index\Index

### CODE REVIEW

**Comment by astorm** [comment]
@QwertyZW I like this -- but with two additional arguments the `magento2:generate:full-module` command will create a shell script that halts, waiting for use input.  If you can have `magento2:generate:full-module` generate the needed default Index Index arguments, I think this one will be good to go.  (happy to explain more if that doesn't make sense)

**Comment by QwertyZW** [comment]
No problem. Will fix. No need for a further explanation, I've used the `magento2:generate:full-module` command  :)

**Comment by QwertyZW** [comment]
Fixed

**Comment by astorm** [comment]
Merged!

**Pull request merged**
